name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        go: [1.18, 1.19]
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3.2.1
        with:
          go-version: ${{ matrix.go }}
      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v ./...
